set(CMAKE_SYSTEM_NAME iOS)
set(CMAKE_SYSTEM_PROCESSOR arm64)

set(CMAKE_OSX_SYSROOT "$ENV{TARGET_SYSROOT}")
set(CMAKE_OSX_ARCHITECTURES arm64)
set(CMAKE_OSX_DEPLOYMENT_TARGET "$ENV{IPHONEOS_DEPLOYMENT_TARGET}")

set(CMAKE_C_COMPILER "$ENV{CC}")
set(CMAKE_CXX_COMPILER "$ENV{CXX}")
set(CMAKE_ASM_COMPILER "$ENV{CC}")

set(CMAKE_AR "$ENV{AR}" CACHE FILEPATH "Archiver")
set(CMAKE_RANLIB "$ENV{RANLIB}" CACHE FILEPATH "Ranlib")
set(CMAKE_STRIP "$ENV{STRIP}" CACHE FILEPATH "Strip")
set(CMAKE_NM "$ENV{NM}" CACHE FILEPATH "NM")
set(CMAKE_LINKER "$ENV{LD}" CACHE FILEPATH "Linker")
set(CMAKE_LIPO "$ENV{LIPO}" CACHE FILEPATH "Lipo")
set(CMAKE_OTOOL "$ENV{OTOOL}" CACHE FILEPATH "Otool")
set(CMAKE_INSTALL_NAME_TOOL "$ENV{I_N_T}" CACHE FILEPATH "Install Name Tool")

set(CMAKE_FIND_ROOT_PATH "$ENV{BUILD_BASE}" "$ENV{TARGET_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# Disable Qt's auto-detection of simulator_and_device
set(QT_UIKIT_SDK "iphoneos" CACHE STRING "")
